fresh_shop_back/fresh_shop_back/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import static

from fresh_shop_back import settings
from utils.upload_images import upload_image

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # homh模块
    url(r'^home/', include('home.urls', namespace='home')),
    # 商品模块
    url(r'^goods/', include('goods.urls', namespace='goods')),
    # 订单模块
    url(r'^orders/', include('orders.urls', namespace='orders')),
    # 编辑器中图片保存
    url(r'^util/upload/(?P<dir_name>[^/]+)$', upload_image, name='upload_image'),
]
# 访问media中的静态资源
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

fresh_shop_back/goods/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from goods import views

urlpatterns = [
    # 商品分类列表
    url(r'^goods_category_list/', login_required(views.goods_category_list), name='goods_category_list'),
    # 商品分类编辑页面
    url(r'^goods_category_edit/(\d+)/', login_required(views.goods_category_edit), name='goods_category_edit'),
    # 商品列表
    url(r'^goods_list/', login_required(views.goods_list), name='goods_list'),
    # 添加商品
    url(r'^goods_add/', login_required(views.goods_add), name='goods_add'),
    # 删除商品
    url(r'^goods_delete/(\d+)/', login_required(views.goods_delete), name='goods_delete'),
    # 商品编辑
    url(r'^goods_edit/(\d+)/', login_required(views.goods_edit), name='goods_edit'),
    # 商品编辑
    url(r'^goods_desc/(\d+)/', login_required(views.goods_desc), name='goods_desc'),
]

fresh_shop_back/home/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from home import views

urlpatterns = [
    #  登录页面
    url(r'^login/', views.login, name='login'),
    # 首页
    url(r'^index/', login_required(views.index), name='index'),
    # 注销
    url(r'^logout/', login_required(views.logout), name='logout'),
]

fresh_shop_back/orders/urls.py
from django.contrib.auth.decorators import login_required
from django.conf.urls import url


from orders import views

urlpatterns = [
    # 订单列表页面
    url('order_list/', login_required(views.order_list), name='order_list'),
]

fresh_shop_back/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    {% block css %}
    {% endblock %}

    {% block js %}
    {% endblock %}
</head>
<body>
{% block header %}
{% endblock %}

{% block aside %}
{% endblock %}

{% block content %}
{% endblock %}

</body>
</html>

fresh_shop_back/templates/base_main.html
{% extends 'base.html' %}

{% block css %}
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
{% endblock %}

{% block js %}
    {% load static %}
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
{% endblock %}

{% block header %}
    {% load static %}
    <header>
        <h1><img src="{% static 'images/admin_logo.png'%}"/></h1>
        <ul class="rt_nav">
            <li><a href="/" target="_blank" class="website_icon">站点首页</a></li>
            <li><a href="#" class="set_icon">账号设置</a></li>
            <li><a href="login.html" class="quit_icon">安全退出</a></li>
        </ul>
    </header>
{% endblock %}

{% block aside %}
    <aside class="lt_aside_nav content mCustomScrollbar">
        <h2><a href="">商城后台菜单栏</a></h2>
        <ul>
            <li>
                <dl>
                    <dt>商品管理</dt>
                    <!--当前链接则添加class:active-->
                    <dd><a href="{% url 'goods:goods_category_list' %}">商品分类</a></dd>
                    <dd><a href="{% url 'goods:goods_list' %}">商品列表</a></dd>
                </dl>
            </li>
            <li>
                <dl>
                    <dt>订单管理</dt>
                    <dd><a href="{% url 'orders:order_list' %}">订单列表</a></dd>
                </dl>
            </li>
            <li>
                    <dl>
                        <dt>用户管理</dt>
                        <dd><a href="user_list.html">用户列表</a></dd>
                    </dl>
                </li>
        </ul>
    </aside>
{% endblock %}

fresh_shop_back/templates/goods_category_detail.html
{% extends 'base_main.html' %}

{% block content %}
    <section class="rt_wrap mCustomScrollbar">

        <div class="rt_content">
            <div class="page_title">
                <h2 class="fl">商品分类详情</h2>
                <a class="fr top_rt_btn" href="goods_category_list.html">返回商品分类列表</a>
            </div>
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <section>
                    <ul class="ulColumn2">
                        <li>
                            <span class="item_name" style="width:120px;">商品分类名称：</span>
                                {% for type in categorys_types %}
                                    {% ifequal type.0 category.id %}
                                        {{ type.1 }}
                                    {% endifequal %}
                                {% endfor %}
                        </li>

                        <li>
                            <span class="item_name" style="width:120px;">上传商品分类首图：</span>

                                <img src="/media/{{ category.category_front_image }}">

                            <label class="uploadImg">
                                 <input type="file" name="category_front_image"/>
                                 <span>上传图片</span>
                            </label>
                        </li>
                        <li>
                            <span class="item_name" style="width:120px;"></span>
                            <input type="submit" class="link_btn"/>
                        </li>
                    </ul>
                </section>
            </form>
        </div>
    </section>
{% endblock %}

fresh_shop_back/templates/goods_category_list.html
{% extends 'base_main.html' %}


{% block content %}
    <section class="rt_wrap content mCustomScrollbar">
        <div class="rt_content">
            <div class="page_title">
                <h2 class="fl">商品分类列表</h2>
                <a href="goods_category_detail.html" class="fr top_rt_btn add_icon">添加商品</a>
            </div>
            <table class="table">
                <tr>
                    <th>缩略图</th>
                    <th>类型</th>
                    <th>操作</th>
                </tr>
                {% for category in categorys %}
                    <tr>
                        <td class="center">
                            <img src="/media/{{ category.category_front_image }}" width="50" height="50" alt="" />
                        </td>
                        <td class="center">
                            {% for type in category_types %}
                                {% ifequal category.category_type type.0 %}
                                    {{ type.1 }}
                                {% endifequal %}
                            {% endfor %}
                        </td>
                        <td class="center">
                            <a href="{% url 'goods:goods_category_edit' category.id %}" title="编辑" class="link_icon">&#101;</a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </section>

{% endblock %}

fresh_shop_back/templates/goods_desc.html
{% extends 'base_main.html' %}

{% block js %}
    {{ block.super }}
    <script type="text/javascript" src="/static/kindeditor/kindeditor-all.js"></script>
    <script type="text/javascript" src="/static/kindeditor/lang/zh-CN.js"></script>
    <script type="text/javascript">
        KindEditor.ready(function(K) {
                window.editor = K.create('#editor_id',{
                    uploadJson:'/util/upload/kindeditor'
                });
        });
    </script>
{% endblock %}

{% block content %}
    <section class="rt_wrap">

        <div class="rt_content">
            <div class="page_title">
                <h2 class="fl">商品详情</h2>
                <a class="fr top_rt_btn" href="/goods/goods_list/">返回商品列表</a>
            </div>
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <section>
                    <ul class="ulColumn2">
                        <li>
                            <span class="item_name" style="width:120px;">产品详情：</span>
                            <label style="display:inline-block;padding:15px;background:#f8f8f8;">
                                <textarea id="editor_id" name="content" style="width:700px;">{{ goods.goods_desc }}</textarea>
                            </label>
                        </li>
                        <li>
                            <span class="item_name" style="width:120px;"></span>
                            <input type="submit" class="link_btn"/>
                        </li>
                    </ul>
                </section>
            </form>
        </div>
    </section>
{% endblock %}

fresh_shop_back/templates/goods_detail.html
{% extends 'base_main.html' %}

{% block content %}
    <section class="rt_wrap mCustomScrollbar">

        <div class="rt_content">
            <div class="page_title">
                <h2 class="fl">商品详情</h2>
                <a class="fr top_rt_btn" href="/goods/goods_list/">返回商品列表</a>
            </div>
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <section>
                    <ul class="ulColumn2">
                        <li>
                            <span class="item_name" style="width:120px;">商品名称：</span>
                            <input type="text" name="name" value="{{ goods.name }}" class="textbox textbox_295" placeholder="商品名称..."/>

                        </li>
                        <li>
                            <span class="item_name" style="width:120px;">商品货号：</span>
                            <input type="text" name="goods_sn" value="{{ goods.goods_sn }}"  class="textbox" placeholder="商品货号..."/>

                        </li>
                        <li>
                            <span class="item_name" style="width:120px;">分类：</span>
                            <select class="select" name="category">
                                {% for type in category_types %}
                                    <option value="{{ type.0 }}"
                                            {% ifequal type.0 goods.category.category_type %}
                                                selected="selected"
                                            {% endifequal %}>
                                        {{ type.1 }}
                                    </option>
                                {% endfor %}
                            </select>

                        </li>
                        <li>
                            <span class="item_name" style="width:120px;">商品库存：</span>
                            <input type="text" name="goods_nums" value="{{ goods.goods_nums }}"  class="textbox textbox_295" placeholder="商品库存..."/>

                        </li>
                        <li>
                            <span class="item_name" style="width:120px;">市场价格：</span>
                            <input type="text" name="market_price" value="{{ goods.market_price }}" class="textbox textbox_295" placeholder="市场价格..."/>

                        </li>
                        <li>
                            <span class="item_name" style="width:120px;">本店价格：</span>
                            <input type="text" name="shop_price" value="{{ goods.shop_price }}" class="textbox textbox_295" placeholder="本店价格..."/>

                        </li>
                        <li>
                            <span class="item_name" style="width:120px;">商品简短描述：</span>
                            <input type="text" name="goods_brief" value="{{ goods.goods_brief }}" class="textbox textbox_295" placeholder="商品简短描述..."/>

                        </li>
                        <li>
                            <span class="item_name" style="width:120px;">上传商品首图：</span>
                            <img src="/media/{{ goods.goods_front_image }}">
                            <label class="uploadImg">
                                 <input type="file" name="goods_front_image"/>
                                 <span>上传图片</span>
                            </label>
                        </li>
                        <!--<li>-->
                            <!--<span class="item_name" style="width:120px;">产品详情：</span>-->

                            <!--<textarea id="editor_id" name="content" style="width:700px;height:300px;">-->
                                <!--&lt;strong&gt;HTML内容&lt;/strong&gt;-->
                            <!--</textarea>-->
                        <!--</li>-->
                        <li>
                            <span class="item_name" style="width:120px;"></span>
                            <input type="submit" class="link_btn"/>
                        </li>
                    </ul>
                </section>
            </form>
        </div>
    </section>

{% endblock %}

fresh_shop_back/templates/goods_list.html
{% extends 'base_main.html' %}

{% block content %}
    <section class="rt_wrap content mCustomScrollbar">
        <div class="rt_content">
            <div class="page_title">
                <h2 class="fl">商品列表</h2>
                <a href="{% url 'goods:goods_add' %}" class="fr top_rt_btn add_icon">添加商品</a>
            </div>
            <table class="table">
                <tr>
                    <th>缩略图</th>
                    <th>产品名称</th>
                    <th>商品类型</th>
                    <th>货号</th>
                    <th>市场单价</th>
                    <th>本店单价</th>
                    <th>库存</th>
                    <th>详情</th>
                    <th>操作</th>
                </tr>
                {% for good in page %}
                    <tr>
                        <td class="center"><img src="/media/{{ good.goods_front_image }}" width="50" height="50" alt="" /></td>
                        <td class="center">{{ good.name }}</td>
                        <td class="center">
                            {% for type in category_types %}
                                {% ifequal good.category.category_type type.0 %}
                                    {{ type.1 }}
                                {% endifequal %}
                            {% endfor %}
                        </td>
                        <td class="center">{{ good.goods_sn }}</td>
                        <td class="center"><strong class="rmb_icon">{{ good.market_price }}</strong></td>
                        <td class="center"><strong class="rmb_icon">{{ good.shop_price }}</strong></td>
                        <td class="center">{{ good.goods_nums }}</td>
                        <td class="center">
                            <a href="{% url 'goods:goods_desc' good.id %}">{{ good.name }}描述</a>
                        </td>
                        <td class="center">
                            <a href="{% url 'goods:goods_edit' good.id %}" title="编辑" class="link_icon">&#101;</a>
                            <a onclick="goods_delete({{ good.id }})" title="删除" class="link_icon">&#100;</a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
            {% csrf_token %}
            <script>
                function goods_delete(id){
                    var csrf = $('input[name="csrfmiddlewaretoken"]').val()
                    $.ajax({
                        url: '/goods/goods_delete/' + id + '/',
                        type:'POST',
                        dataType:'json',
                        headers:{'X-CSRFToken': csrf},
                        success:function(data){
                            if(data.code == '200'){
                                location.href = '/goods/goods_list/'
                            }
                        },
                        error: function(data){
                            alert('请求失败')
                        }
                    })
                }
            </script>
            <aside class="paging">
                <a>当前{{ page.number }}页</a>
                <a href="{% url 'goods:goods_list' %}">第一页</a>
                    {% for i in page.paginator.page_range %}
                        <a href="{% url 'goods:goods_list' %}?page={{ i }}">{{ i }}</a>
                    {% endfor %}
                <a href="{% url 'goods:goods_list' %}?page={{ page.paginator.num_pages }}">最后一页</a>
            </aside>
        </div>
    </section>

{% endblock %}

fresh_shop_back/templates/index.html
{% extends 'base_main.html' %}

{% block content %}
    <section class="rt_wrap content mCustomScrollbar">
        <div class="rt_content">
            <h1 style="color:red;font-size:20px;font-weight:bold;text-align:center;">
                生鲜商城管理后台
            </h1>
            <br>
            <p>商城管理采用Django1.11 + Python3.6开发，存储数据库为关系型数据库Mysql</p>
            <br>
            <p>商城后台集中功能为：商品分类、商品图片、商品库存、用户管理、收货地址管理、留言管理、订单管理等模块</p>
        </div>
    </section>
{% endblock %}

fresh_shop_back/templates/login.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>后台登录</title>
<meta name="author" content="DeathGhost" />
 {% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
<style>
body{height:100%;background:#16a085;overflow:hidden;}
canvas{z-index:-1;position:absolute;}
</style>
<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/verificationNumbers.js' %}"></script>
<script src="{% static 'js/Particleground.js' %}"></script>
<script>
$(document).ready(function() {
  //粒子背景特效
  $('body').particleground({
    dotColor: '#5cbdaa',
    lineColor: '#5cbdaa'
  });
  //验证码
  createCode();
  //测试提交，对接程序删除即可
  $(".submit_btn").click(function(){
	  location.href="index.html";
	  });
});
</script>
</head>
<body>
<dl class="admin_login">
 <dt>
  <strong>站点后台管理系统</strong>
  <em>Management System</em>
 </dt>
    <form action="" method="post">
        {% csrf_token %}
        <dd class="user_icon">
            {{ form.errors.username }}
            <input type="text" placeholder="账号" name="username" class="login_txtbx"/>
        </dd>
        <dd class="pwd_icon">
            {{ form.errors.password }}
            <input type="password" placeholder="密码" name="password" class="login_txtbx"/>
        </dd>
        <dd>
            <input type="submit" value="立即登录" class="submit_btn"/>
        </dd>
    </form>
 <dd>
  <p>© 2015-2016 DeathGhost 版权所有</p>
  <p>陕B2-20080224-1</p>
 </dd>
</dl>
</body>
</html>

fresh_shop_back/templates/order_list.html
{% extends 'base_main.html' %}


{% block content %}

<section class="rt_wrap content mCustomScrollbar">
    <div class="rt_content">
        <div class="page_title">
            <h2 class="fl">订单列表</h2>
        </div>
        <table class="table">
            <tr>
                <th>订单编号</th>
                <th>收件人</th>
                <th>联系电话</th>
                <th>收件人地址</th>
                <th>订单金额</th>
                <th>配送方式</th>
                <!--<th>操作</th>-->
            </tr>
            {% for order_info in page %}
                <tr>
                    <td class="center">{{ order_info.order_sn|slice:"20" }}</td>
                    <td>{{ order_info.signer_name }}</td>
                    <td>{{ order_info.signer_mobile }}</td>
                    <td>
                        <address>{{ order_info.address }}</address>
                    </td>
                    <td class="center"><strong class="rmb_icon">{{ order_info.order_mount }}</strong></td>
                    <td class="center">申通快递</td>
                    <!--<td class="center">-->
                        <!--<a href="#" title="查看订单" class="link_icon" target="_blank">&#118;</a>-->
                    <!--</td>-->
                </tr>
            {% endfor %}
        </table>
        <aside class="paging">
            <a>当前{{ page.number }}页</a>
            <a href="{% url 'orders:order_list' %}">第一页</a>
            {% for i in page.paginator.page_range %}
                <a href="{% url 'orders:order_list' %}?page={{ i }}"> {{ i }} </a>
            {% endfor %}
            <a href="{% url 'orders:order_list' %}?page={{ page.paginator.num_pages }}">最后一页</a>
        </aside>
    </div>
</section>

{% endblock %}

fresh_shop_back/templates/user_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>

    </title>

    <link rel="stylesheet" type="text/css" href="css/style.css">

    <script src="js/jquery.js"></script>
    <script src="js/jquery.mCustomScrollbar.concat.min.js"></script>

</head>
<body>


<header>
    <h1><img src="images/admin_logo.png"/></h1>
    <ul class="rt_nav">
        <li><a href="/" target="_blank" class="website_icon">站点首页</a></li>
        <li><a href="#" class="set_icon">账号设置</a></li>
        <li><a href="login.html" class="quit_icon">安全退出</a></li>
    </ul>
</header>




    <aside class="lt_aside_nav content mCustomScrollbar">
        <h2><a href="">商城后台菜单栏</a></h2>
        <ul>
            <li>
                <dl>
                    <dt>商品管理</dt>
                    <!--当前链接则添加class:active-->
                    <dd><a href="goods_category_detail.html">商品分类</a></dd>
                    <dd><a href="goods_list.html">商品列表</a></dd>
                </dl>
            </li>
            <li>
                <dl>
                    <dt>订单管理</dt>
                    <dd><a href="order_list.html">订单列表</a></dd>
                </dl>
            </li>
            <li>    
                <dl>
                    <dt>用户管理</dt>
                    <dd><a href="user_list.html">用户列表</a></dd>
                </dl>
            </li>
            </ul>
    </aside>

    <style>
    .dataStatistic{width:400px;height:200px;border:1px solid #ccc;margin:0 auto;margin:10px;overflow:hidden}
    #cylindrical{width:400px;height:200px;margin-top:-15px}
    #line{width:400px;height:200px;margin-top:-15px}
    #pie{width:400px;height:200px;margin-top:-15px}
    </style>

<section class="rt_wrap content mCustomScrollbar">
 <div class="rt_content">
      <div class="page_title">
       <h2 class="fl">会员列表</h2>
       <a href="user_detail.html" class="fr top_rt_btn add_icon">添加新会员</a>
      </div>
      <section class="mtb">
       <select class="select">
        <option>会员等级</option>
        <option>普通会员</option>
        <option>高级会员</option>
       </select>
       <input type="text" class="textbox textbox_225" placeholder="输入会员号/手机/电子邮件查询..."/>
       <input type="button" value="查询" class="group_btn"/>
      </section>
      <table class="table">
       <tr>
        <th>Id</th>
        <th>会员头像</th>
        <th>会员账号</th>
        <th>手机号码</th>
        <th>电子邮件</th>
        <th>验证</th>
        <th>会员等级</th>
        <th>账户余额</th>
        <th>冻结资金</th>
        <th>操作</th>
       </tr>
       <tr>
        <td class="center">001</td>
        <td class="center"><img src="upload/user_002.png" width="50" height="50"/></td>
        <td>DeathGhost</td>
        <td class="center">18300000000</td>
        <td class="center">deathghost@sina.cn</td>
        <td class="center"><a title="已验证" class="link_icon">&#89;</a></td>
        <td class="center">普通会员</td>
        <td class="center">
         <strong class="rmb_icon">5559.00</strong>
        </td>
        <td class="center">
         <strong class="rmb_icon">59.00</strong>
        </td>
        <td class="center">
         <a href="user_detail.html" title="编辑" class="link_icon">&#101;</a>
         <a href="#" title="删除" class="link_icon">&#100;</a>
        </td>
       </tr>
       <tr>
        <td class="center">002</td>
        <td class="center"><img src="upload/user_001.png" width="50" height="50"/></td>
        <td>DeathGhost02</td>
        <td class="center">15800000000</td>
        <td class="center">232650413@sina.cn</td>
        <td class="center"><a title="未验证" class="link_icon">&#88;</a></td>
        <td class="center">高级会员</td>
        <td class="center">
         <strong class="rmb_icon">199.00</strong>
        </td>
        <td class="center">
         <strong class="rmb_icon">15.00</strong>
        </td>
        <td class="center">
         <a href="user_detail.html" title="编辑" class="link_icon">&#101;</a>
         <a href="#" title="删除" class="link_icon">&#100;</a>
        </td>
       </tr>
      </table>
      <aside class="paging">
       <a>第一页</a>
       <a>1</a>
       <a>2</a>
       <a>3</a>
       <a>…</a>
       <a>1004</a>
       <a>最后一页</a>
      </aside>
 </div>
</section>
</body>
</html>